services:
  - type: web
    name: Hibiscan-Beta
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_fastapi:app --host 0.0.0.0 --port 10000

